### ISSUE TITLE
Demo Extension : Create datasets

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1078]
The demo extension should allow the demo environment to be loaded with demo specific data. Currently this data is being loaded via a rake task in core

Datasets should include
  - Projects
      - Project questions should make sense
  - Products
  - Product Categories
  - Orders
  - Services
  - Wizard Questions
  - In general
    - Use variable length Lorem ipsum text for descriptions. Something like one to 5 paragraphs should do.
    - Tags for things should make sense
    - Alerts for various objects
      - Alerts should make sense and should not be assigned arbitrarily. 
    - Answers for various objects
      - Answers should make sense and should not be assigned arbitrarily. 

- [ ] Create datasets
  - [ ] Federal dataset
  - [ ] Health dataset
  - [x] Generic dataset

Belongs to #955

**Comment by mafernando** [comment]
Closing this since each dataset specified is now being tracked on its own issue.

For reference:
- [Federal Dataset Issue](https://github.com/boozallen/projectjellyfish/issues/1098)
- [Health Dataset Issue](https://github.com/boozallen/projectjellyfish/issues/1099)
- [Generic Dataset Issue](https://github.com/boozallen/projectjellyfish/issues/1100)
