### ISSUE TITLE
Demo Extension : Server product type

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1103]
This product type should create a server service when added to a project.

Product types should include
  - Include product and order questions
  - Service outputs from the provisioning process
  - Optionally use a service details page override

**Comment by mafernando** [comment]
Need to add back service outputs - using same product type for the `sample:demo` products currently.

**Comment by mafernando** [comment]
Per the initial request:
- [x] server product type (See product type implementation [here](https://github.com/mafernando/jellyfish-demo/blob/feature/1100-generic-dataset/app/models/jellyfish_demo/product_type/server.rb) and service implementation [here](https://github.com/mafernando/jellyfish-demo/blob/feature/1100-generic-dataset/app/models/jellyfish_demo/service/server.rb))
- ~~server product type order questions~~  - couldn't get this one because order questions aren't appearing in the cart atm. See https://github.com/boozallen/projectjellyfish/issues/1141 for conetext.
- [x] service outputs (See [here](https://github.com/mafernando/jellyfish-demo/blob/feature/1100-generic-dataset/app/models/jellyfish_demo/service/server.rb#L17-L33))
- ~~service details override~~ leaving this one out because it was initially stated as optional.

Full implementation contained in PR https://github.com/projectjellyfish/jellyfish-demo/pull/8

**Comment by mafernando** [comment]
Closed https://github.com/boozallen/projectjellyfish/pull/1142.
