### ISSUE TITLE
Resolve DEPRECATION warnings in build log

### ISSUE THREAD

**Issue by chriskacerguis** [boozallen/projectjellyfish#1133]
Seeing a LOT of this in the build log, we need to resolve that
````
DEPRECATION WARNING: ProductType.service_class will be removed in a future update, use Product.service_class instead. (called from service_class at /home/travis/build/boozallen/projectjellyfish/app/models/product.rb:48)
````

**Comment by mafernando** [comment]
The deprecation warnings are caused by `ProductType` calls to the [`order_questions`](https://github.com/boozallen/projectjellyfish/blob/master/app/models/product_type.rb#L58-L61) method or the [`service_class`](https://github.com/boozallen/projectjellyfish/blob/master/app/models/product_type.rb#L67-L70) method . 

Those methods are called from the following files in core:
- [product_serializer.rb](https://github.com/boozallen/projectjellyfish/blob/master/app/serializers/product_serializer.rb#L29)
- [products_controller.rb](https://github.com/boozallen/projectjellyfish/blob/master/app/controllers/products_controller.rb#L77)
- [ create.state.js](https://github.com/boozallen/projectjellyfish/blob/develop/app/assets/javascripts/app/states/orders/create/create.state.js#L59) (orders)

The current `jellyfish-aws` and `jellyfish-demo` extensions rely on the those methods being defined against `ProductType` but the `jellyfish-azure` extension looks for them on `Product`.

Should we change the demo and aws extensions to align with azure or the other way around? 

Have been looking at the `jellyfish-azure`, but its not clicking how products are being loaded in addition to product types. 

Also not sure if having `service class` on product is a change we need to make.

Note: Either way, order questions do not appear in the current cart implementation. 

@stackus - any thoughts?

**Comment by stackus** [comment]
That is exactly what the deprecation message is telling you to do. Create the `Product` classes you need and set the `service_class` correctly.

**Comment by mafernando** [comment]
ToDo:
- [ ] Move `order_questions` and `service_class` to Product class from ProductType in `jellyfish-demo`
- [ ] Move `order_questions` and `service_class` to Product class from ProductType in `jellyfish-aws`
- [ ] Move `order_questions` and `service_class` to Product class from ProductType in core to resolve deprecation warnings in build logs AND reference the latest `jellyfish-demo` extension in Gemfile.lock
