### ISSUE TITLE
Issues Setting up DB

### ISSUE THREAD

**Issue by nickbisson** [boozallen/projectjellyfish#1138]
I've just installed jellyfish in a docker container and is running on port 3000. However, proceeding to the database installation instructions, trying to run docker-compose run web rake db:setup results in this error: 
![image](https://cloud.githubusercontent.com/assets/17887547/14538184/6b76080c-0248-11e6-833a-f7f170ffe505.png)

Win7 using gitbash as shell.

**Comment by chriskacerguis** [comment]
Not sure we can help that one. Looks like an issue with Docker on Windows. Maybe ping Docker on that.

**Comment by watkinsc** [comment]
Instead of using docker-compose run, you _might_ be able to exec into the container (so long as it is running) and run the rake commands from there.

From a shell, run `docker ps` and get the **Container ID** of your running Jellyfish. (Should have the image name 'projectjellyfish_web').

Next, use the docker exec command to enter a bash shell inside your running container:
`docker exec -it **CONTAINER ID** bash`

Once in the shell, run the rake commands:
```
rake db:setup
rake db:seed
rake sample:demo
```
Then, exit the shell using `exit`.

**Comment by nickbisson** [comment]
@watkinsc thanks for the advice. running the first command leads to this:

![image](https://cloud.githubusercontent.com/assets/17887547/14540302/5665bf84-0252-11e6-96e9-8aededb63a60.png)

Doing a little research (http://stackoverflow.com/questions/29380344/docker-exec-it-command-returns-following-error-cannot-enable-tty-mode-on-non-t) shows me this command as the fix: " winpty docker exec -it <containerIdOrName> bash "

This is the result of the of commands:

![image](https://cloud.githubusercontent.com/assets/17887547/14540371/a93c23ba-0252-11e6-9c47-c1304cdcc257.png)

**Comment by watkinsc** [comment]
Hm. It looks like your docker exec command is working now, however we're not in the correct container. We need to exec into the _web_ container, as it is what holds the rake tasks we're trying to run.

`docker-compose up` should create two containers, `projectjellyfish_web_1` and `projectjellyfish_db_1`. Currently, it appears your database container is running, but the web container is not. For reference, here is my `docker ps` output with both containers.
![screen shot 2016-04-14 at 3 14 31 pm](https://cloud.githubusercontent.com/assets/18466611/14540562/af051a62-0253-11e6-9415-b847ed1e6aaa.png)

In order to get the web container running again, lets try the following:

1. `docker ps -a` to display a list of _all_ containers, running or stopped.
2. From this list, see if you have a container that matches the `IMAGE: projectjellyfish_web`
3. If you do, copy the `CONTAINER ID` and run `docker start **CONTAINER ID**`
4. Once you've done the following, re-run `docker ps` to confirm the container has successfully started again.
5. Proceed with the previous steps to run the rake tasks, but instead exec into the projectjellyfish_web container (the container you just started).


**If the above does not work AND you do not have a projectjellyfish_web container when you run `docker ps -a` do the following:**
1. `docker stop **CONTAINER ID**` where CONTAINER ID is the currently running postgres container (from your screenshot, its ID would be `5934c41b4b3f`)
2. From your project root re-run `docker-compose up` to re-create and start the containers associated with Jellyfish
3. Proceed with the previous steps to run the rake tasks, but instead exec into the projectjellyfish_web container.

Hope this helps!

**Comment by nickbisson** [comment]
@watkinsc looks like there is an issue with the web container. Here is steps 1-4:
![image](https://cloud.githubusercontent.com/assets/17887547/14541470/239e05ba-0258-11e6-84de-255f3ee89538.png)

Looks like the container does not start. Stopping running containers in step 1 and confirmed no running containers:
![image](https://cloud.githubusercontent.com/assets/17887547/14541499/3c78eec4-0258-11e6-8b72-4ec6426d4a76.png)

Here is step 2:
![image](https://cloud.githubusercontent.com/assets/17887547/14541515/5257344e-0258-11e6-822a-186751f5dd06.png)

Web container exits on launch with code 1.

**Comment by watkinsc** [comment]
Without delving into too much detail, that issue stems from the container not shutting down properly, or the server.pid file not being removed on startup. [a bit more on it here..](https://github.com/docker/compose/issues/1393)

We've got two options - we can either remove the old docker containers (once stopped) and re-create them, or we can edit the docker-compose file. I'll leave it up to you.

**Option 1: Removing old containers**
1. Stop any running docker containers associated with Project Jellyfish
2. List your docker containers `docker ps -a`
3. Run `docker rm **CONTAINER ID**` on the containers associated with Project Jellyfish
4. Re-run docker-compose up from project root

**Option 2: Editing docker-compose.yml**
1. Stop any running docker containers associated with Project Jellyfish
2. Edit your `docker-compose.yml` file. This is located in your project root.
The 4th line of your docker-compose file should currently read:
`command: bundle exec rails s -p 3000 -b '0.0.0.0'`
Modify it to remove the server.pid file on startup:
` command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"`
3. Save and re-run `docker-compose up`

Once you're able to start both containers again, we should be able to go back to exec-ing into the projectjellyfish_web container and running the rake commands!

**Comment by nickbisson** [comment]
@watkinsc working! Thank you! (used option 2).
